kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    icinga.gooddata.io/owner: "tma"
    icinga.gooddata.io/scrape: "true"
    icinga.gooddata.io/services: "gooddata-ruby-{{ jobName }}"
    icinga.gooddata.io/smart_services: |
      max_restarts: 5,10
      min_replicas: 0,0
  name: {{ $jobName }}
  labels:
    app: gooddata-ruby
    component: bricks
    team: tma
    chart: "{{ $jobName }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gooddata-ruby
        component: bricks
        team: tma
    spec:
      containers:
      - name: ruby
        {{- with index .Values "gooddata-ruby" "brick" "image" }}
        image: "{{ .registry }}/{{ .namespace }}/hello-world-brick:{{ .tag }}"
        {{- end }}
        command: []

